### ISSUE TITLE
Application fails from fresh install

### ISSUE THREAD

**Issue by S-Stephen** [eric-wieser/engineering-calendar#3]
from a fresh install using the requirements.txt file the application no longer works. 

error:                                                                                 

```
 SyntaxError: invalid syntax 
Traceback (most recent call last): 
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker 
      worker.init_process() 
    File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process 
      self.wsgi = self.app.wsgi() 
    File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi 
      self.callable = self.load() 
    File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load 
      return self.load_wsgiapp() 
    File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp 
      return util.import_app(self.app_uri) 
    File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app 
      __import__(module) 
    File "/app/main.py", line 6, in <module> 
      from objects import CourseYear 
    File "/app/objects.py", line 160 
      raise NoTermData("No data for example papers in term {!r}".format(name)) from e 
```

on building app (now):

```
 Obtaining bottle from git+git://github.com/bottlepy/bottle.git@854fbd7f88aa2f809f54dd724aea7ecf918a3b6e#egg=bottle (from -r requirements.txt (line 8))
         Cloning git://github.com/bottlepy/bottle.git (to 854fbd7f88aa2f809f54dd724aea7ecf918a3b6e) to ./.heroku/src/bottle
         Could not find a tag or branch '854fbd7f88aa2f809f54dd724aea7ecf918a3b6e', assuming commit.
       Installing collected packages: six, python-dateutil, pytz, icalendar, wheel, xlrd, gunicorn, bottle
         Running setup.py install for icalendar: started
           Running setup.py install for icalendar: finished with status 'done'
         Running setup.py install for xlrd: started
           Running setup.py install for xlrd: finished with status 'done'
         Running setup.py develop for bottle
       Successfully installed bottle gunicorn-19.3.0 icalendar-3.9.1 python-dateutil-2.4.2 pytz-2015.6 six-1.10.0 wheel-0.24.0 xlrd-0.9.4
```

where before (producing successful deployment):

```
pip install -r requirements.txt
       Obtaining bottle from git+git://github.com/bottlepy/bottle.git@854fbd7f88aa2f809f54dd724aea7ecf918a3b6e#egg=bottle (from -r requirements.txt (line 8))
         Cloning git://github.com/bottlepy/bottle.git (to 854fbd7f88aa2f809f54dd724aea7ecf918a3b6e) to ./.heroku/src/bottle
         Could not find a tag or branch '854fbd7f88aa2f809f54dd724aea7ecf918a3b6e', assuming commit.
       Installing collected packages: bottle
         Running setup.py develop for bottle
       Successfully installed bottle-0.12.8
```

**Comment by S-Stephen** [comment]
appeared to be an issue with the default underlying version of python used.

**Comment by eric-wieser** [comment]
Can you elaborate on that remark?
